<%@ Page Title="" Language="C#" MasterPageFile="~/Site.master" AutoEventWireup="true" CodeFile="read_record.aspx.cs" Inherits="read_record" %>

<asp:Content ID="Content1" ContentPlaceHolderID="MainContent" Runat="Server">

    <br />
        <br />

    <br />
    <asp:GridView ID="GridView3" runat="server" 
        AutoGenerateDeleteButton="True" 
        AutoGenerateEditButton="True" 
        CellPadding="4" 
        DataSourceID="SqlDataSource3" 
        ForeColor="#333333" AllowPaging="True" AllowSorting="True" Font-Names="Century Gothic" GridLines="None" OnSelectedIndexChanged="GridView3_SelectedIndexChanged1" PageSize="3" Width="700px" AutoGenerateColumns="False" BorderStyle="Double" CellSpacing="4" CssClass="active">
        <AlternatingRowStyle BorderColor="#33CCFF" BorderStyle="Dashed" Font-Names="Century Gothic" BorderWidth="1px" BackColor="White" />
        <Columns>
            <asp:BoundField DataField="Nome" HeaderText="Nome" SortExpression="Nome" />
            <asp:BoundField DataField="Apelido" HeaderText="Apelido" SortExpression="Apelido" />
            <asp:BoundField DataField="Email" HeaderText="Email" SortExpression="Email" />
            <asp:BoundField DataField="Morada" HeaderText="Morada" SortExpression="Morada" />
            <asp:BoundField DataField="Localidade" HeaderText="Localidade" SortExpression="Localidade" />
            <asp:BoundField DataField="CodPostal" HeaderText="CodPostal" SortExpression="CodPostal" />
            <asp:BoundField DataField="Telefone" HeaderText="Telefone" SortExpression="Telefone" />
            <asp:BoundField DataField="DataNascimento" HeaderText="DataNascimento" SortExpression="DataNascimento" />
            <asp:BoundField DataField="Password" HeaderText="Password" SortExpression="Password" />
            <asp:BoundField DataField="Username" HeaderText="Username" SortExpression="Username" />
        </Columns>
        <FooterStyle BackColor="#990000" Font-Bold="True" ForeColor="White" />
        <HeaderStyle BackColor="#990000" Font-Bold="True" ForeColor="White" />
        <PagerStyle BackColor="#FFCC66" ForeColor="#333333" HorizontalAlign="Center" />
        <RowStyle BackColor="#FFFBD6" ForeColor="#333333" />
        <SelectedRowStyle BackColor="#FFCC66" Font-Bold="True" ForeColor="Navy" />
        <SortedAscendingCellStyle BackColor="#FDF5AC" />
        <SortedAscendingHeaderStyle BackColor="#4D0000" />
        <SortedDescendingCellStyle BackColor="#FCF6C0" />
        <SortedDescendingHeaderStyle BackColor="#820000" />
    </asp:GridView>
    <asp:SqlDataSource ID="SqlDataSource3" runat="server" ConnectionString="<%$ ConnectionStrings:DefaultConnection %>" 
        SelectCommand="SELECT [Nome], [Apelido], [Email], [Morada], [Localidade], [CodPostal], [Telefone], [DataNascimento], [Password], [Username] FROM [Pessoas]">
    </asp:SqlDataSource>

    <br />


</asp:Content>

<%--Implement paging in an asp.net gridview that uses sqldatasource - Part 50--%>
<%--https://www.youtube.com/watch?v=63GTkVLj9kw--%>